### ISSUE TITLE
Some questions about the README and examples.

### ISSUE THREAD

**Issue by 2455DD** [kyegomez/RT-2#11]
Hi there, thanks for your inspiring works about RT-2! Though your README is really with effort, I have some questions about how to use this repo.

1. What is the `rt2` in "Forward Pass" part? It doesn't show in the context, and I believe it doesn't mean the library (i.e. `import rt2`) since rt2 is not callable.
2. The shape of the tensor `video` in the "Forward Pass" part is not the same as the shape of the tensor with the same name in "Initialization" part. 
3. I'm really wondering what the "video" tensor is about since it's just a tensor with random values and the paper doesn't contain any related information about it. 
4. It seems that the example in `tests` module doesn't work since the `rt2.experimental` is deprecated (or rather, deleted), is it possible to fix it?

btw: is this repo the official implementation of RT-2? If not, is it possible to mention it in your README?
Thank you for your help!

**Comment by kyegomez** [comment]
@2455DD Hello, 

1, 2 the readme was changed these examples are outdated, I forgot to change them. 

And, 3 -> yes it is a tensor of random values as it is an example forward pass to pass some random inputs into the model. They are processing videos.

And, 4 yes, experimental has been deprecated. I shall update it.

And, This is not the official implementation of RT-2, I mention this with "Democratization" in the description of the repo, and I never said it was the official implementation. 

Google would not release this model whatsoever.
