### ISSUE TITLE
run test.py error

### ISSUE THREAD

**Issue by briller-zzj** [kyegomez/RT-2#18]
when I run the file test.py, it fails:
TypeError: 'RT2' object is not callable.

can you help me solve this bug?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/RT-2/issues/18">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/RT-2/issues/18/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/RT-2/issues/18/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@briller-zzj I have fixed it please try again

**Comment by briller-zzj** [comment]
> @briller-zzj I have fixed it please try again
Thanks for reply! Now I can run example.py successfully
But for test.py， it also failed 13/15， only passed 2/15.
Most of the errors are as follows：
AttributeError: 'tuple' object has no attribute 'shape'.

Can you help me solve it?

**Comment by kyegomez** [comment]
@briller-zzj yes I'm solving this error now, we need to unfurl the embeddings in the tuple
