### ISSUE TITLE
Error running example.py

### ISSUE THREAD

**Issue by kinghchan** [kyegomez/RT-2#19]
Hello,

I got the error 'RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x4 and 512x512)' when running the example.py script. I'm at commit e17ceb4fd9cd671f952736848c0bebdd712483ee.  

Please could you help me with what the error means?

Thank you very much!

KC 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/RT-2/issues/19">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/RT-2/issues/19/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/RT-2/issues/19/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@kinghchan update your zeta package 


pip3 install --upgrade zetascale

**Comment by kinghchan** [comment]
@kyegomez thank you very much, that worked!
