### ISSUE TITLE
palme in model is not work

### ISSUE THREAD

**Issue by yeyan00** [kyegomez/RT-2#3]
rt2 model use PALME

in palme project, palme forward params as follow:
![image](https://github.com/kyegomez/RT-2/assets/8616560/1ee5f139-d947-42bb-be91-599e4a8b0316)

but in rt2 model，use like this, params is not same.
![image](https://github.com/kyegomez/RT-2/assets/8616560/3ac0762c-c106-4dbf-a21c-2791066cf4e8)

**Comment by kyegomez** [comment]
@yeyan00 Hey please excuse me! I was trying to integrate the cond_drop into palm e but I have delayed it further, now I just implemented everything from scratch but I will soon implement PalmE again.
