### ISSUE TITLE
I can't install ```palme``` package using ```pip install```

### ISSUE THREAD

**Issue by DoranLyong** [kyegomez/RT-2#5]
![Screenshot from 2023-08-11 21-34-41](https://github.com/kyegomez/RT-2/assets/13333380/80d8a5ae-8a6f-425c-9b55-0c39b48a0fa2)

How to install ```torchlion-pytorch``` ? 

```pip install torchlion-pytorch``` doesn't work...

**Comment by kyegomez** [comment]
@DoranLyong @aakb101 Hey please excuse me over this small issue it is fixed now.
