### ISSUE TITLE
ImportError: cannot import name 'PALME' from 'rt2.experimental.rt2_palme' 

### ISSUE THREAD

**Issue by rahuldeo2047** [kyegomez/RT-2#8]
Thanks for the great RT2. The setup is getting better with time. And yet to learn how to use it.

When I run the following command I get errors as follows:

 ```
$ python tests/test.py 
 Traceback (most recent call last):
  File "tests/test.py", line 3, in <module>
    from rt2.experimental.rt2_palme import PALME, RT2
ImportError: cannot import name 'PALME' from 'rt2.experimental.rt2_palme' (<path_to_env>/lib/python3.8/site-packages/rt2/experimental/rt2_palme.py)
```

How to find the correct PALME library?
the
`$ pip install palme
` installs. However, the error.

**Comment by rahuldeo2047** [comment]
Using tag 0.0.3

**Comment by aakb101** [comment]
Try this in that line:
from rt2.experimental.rt2_palme import PalmE, RT2

**Comment by kyegomez** [comment]
@rahuldeo2047 and @aakb101 Please excuse me for the issues, try again when you have a chance they might be fixed

**Comment by rahuldeo2047** [comment]
@kyegomez and @aakb101 : Thanks for the pointer.

I now get following error:

$ python example.py 
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    rt2 = RT2()
  File "<@beartype(rt2.experimental.rt2_palme.RT2.__init__) at 0x7f541c16cee0>", line 41, in __init__
TypeError: __init__() missing 1 required keyword-only argument: 'palme'
